
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    container_name: prometheus
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana-data/:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-config.yaml" ]
    volumes: [ "./otel-collector.yaml:/etc/otel-config.yaml:ro" ]
    container_name: otel-collector
    ports:
      - "4317:4317"   # OTLP gRPC
#      - "4318:4318"   # OTLP HTTP
      - "9464:9464"   # Prometheus /metrics
    networks:
      - monitoring

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # UI
      - "14250:14250" # gRPC
      - "4319:4317"
    container_name: jaeger
    networks:
      - monitoring
networks:
  monitoring:
    driver: bridge